"use client";
import {useState} from 'react';
import Link from 'next/link';
import {BookOpen,ArrowUpRight,CalendarCheck,CalendarDays,ChevronRight,FileBarChart2,FlaskConical,Layers3,LayoutDashboard,LogOut,Menu,PieChart,Ruler,TrendingUp,Upload,X} from 'lucide-react';
import {ThemeToggle} from '@/components/theme-toggle';
import {UpcomingDeadlines} from '@/components/upcoming-deadlines';
import {MemberAvatar} from '@/components/member-avatar';
import {MemberAvatarUpload} from '@/components/member-avatar-upload';
import {SidebarQuote} from '@/components/sidebar-quote';
import {WeeklyReviewDialog} from '@/components/weekly-review-dialog';
import {AnalyticsDialog} from '@/components/analytics-dialog';
import {TowelAnalysisDialog} from '@/components/towel-analysis-dialog';
import type {Member,Task} from '@/lib/types';
export type StudioView='overview'|'tasks'|'samples'|'planner'|'uploads'|'report'|'diary';
const nav=[{id:'overview',label:'팀 오버뷰',icon:LayoutDashboard},{id:'tasks',label:'업무 보드',icon:Layers3},{id:'samples',label:'샘플 제직',icon:FlaskConical},{id:'planner',label:'일정 · 할 일',icon:CalendarDays},{id:'diary',label:'내 다이어리',icon:BookOpen},{id:'uploads',label:'업로드 기록',icon:Upload}] as const;
type Props={children:React.ReactNode;member:Member;tasks:Task[];active:StudioView;onNavigate?:(view:StudioView)=>void;onSwitchMember?:()=>void};
export function StudioShell({children,member,tasks,active,onNavigate,onSwitchMember}:Props){
 const [mobile,setMobile]=useState(false);const label=active==='report'?'부서장님 보고':nav.find(n=>n.id===active)?.label;
 return <div className="studio-app"><a className="studio-skip" href="#studio-main">본문으로 이동</a><aside className={`studio-sidebar ${mobile?'is-open':''}`}><div className="studio-brand"><Link href="/" aria-label="송월 R&D 대시보드"><img src="/songwol-logo.png" alt="SONGWOL"/></Link><button className="studio-mobile-close" aria-label="메뉴 닫기" onClick={()=>setMobile(false)}><X size={20}/></button></div><div className="studio-workspace"><span><svg width="26" height="26" viewBox="0 0 28 28" fill="none" aria-hidden="true"><path d="M7 3v22M14 3v22M21 3v22" stroke="currentColor" strokeWidth="3" strokeLinecap="round" opacity=".38"/><path d="M3 7h22M3 14h22M3 21h22" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/><path d="M7 4.5v5M21 4.5v5M14 11.5v5M7 18.5v5M21 18.5v5" stroke="var(--studio-wine-soft)" strokeWidth="6"/><path d="M7 4.5v5M21 4.5v5M14 11.5v5M7 18.5v5M21 18.5v5" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg></span><div><strong>디자인 R&D</strong><small>Team workspace</small></div><ChevronRight size={14}/></div><span className="studio-nav-label">WORKSPACE</span><nav aria-label="주 메뉴">{nav.map(n=>onNavigate?<button key={n.id} className={`studio-nav-item ${active===n.id?'is-active':''}`} aria-current={active===n.id?'page':undefined} onClick={()=>{onNavigate(n.id);setMobile(false)}}><n.icon size={18}/>{n.label}{n.id==='tasks'&&<small>{tasks.length}</small>}</button>:<Link className={`studio-nav-item ${active===n.id?'is-active':''}`} key={n.id} href={n.id==='overview'?'/':`/#${n.id}`}><n.icon size={18}/>{n.label}</Link>)}</nav><span className="studio-nav-label studio-tools-label">INSIGHTS & TOOLS</span><div className="studio-tools"><WeeklyReviewDialog tasks={tasks} trigger={<button className="studio-nav-item"><CalendarCheck size={18}/>주간 팀 리뷰</button>}/><AnalyticsDialog tasks={tasks} trigger={<button className="studio-nav-item"><PieChart size={18}/>팀 분석</button>}/><TowelAnalysisDialog trigger={<button className="studio-nav-item"><Ruler size={18}/>타월 사종분석</button>}/><a className="studio-nav-item" href="/sales-dashboard.html" target="_blank" rel="noopener noreferrer"><TrendingUp size={18}/>판매 대시보드<ArrowUpRight size={14}/></a><Link className={`studio-nav-item ${active==='report'?'is-active':''}`} href="/report"><FileBarChart2 size={18}/>부서장님 보고<ArrowUpRight size={14}/></Link></div><div className="studio-sidebar-bottom"><SidebarQuote/><div className="studio-profile"><MemberAvatarUpload member={member}/><button className="studio-profile-info" onClick={onSwitchMember} disabled={!onSwitchMember}><span><strong>{member}</strong><small>디자인 R&D팀</small></span>{onSwitchMember&&<LogOut size={16}/>}</button></div></div></aside>{mobile&&<button className="studio-nav-backdrop" aria-label="메뉴 닫기" onClick={()=>setMobile(false)}/>}
 <div className="studio-main"><header className="studio-topbar"><div className="studio-breadcrumb"><button className="studio-mobile-menu" onClick={()=>setMobile(true)} aria-label="메뉴 열기"><Menu size={21}/></button><span>디자인 R&D</span><ChevronRight size={13}/><strong>{label}</strong></div><div className="studio-top-controls"><span className="studio-today">{new Date().toLocaleDateString('ko-KR',{month:'long',day:'numeric',weekday:'short'})}</span><UpcomingDeadlines tasks={tasks}/><ThemeToggle/><MemberAvatar member={member} variant="studio-avatar"/></div></header><main id="studio-main" className="studio-content">{children}<footer className="studio-footer"><span>SONGWOL <span>DESIGN & RESEARCH</span></span><span>함께 기록하고, 함께 성장합니다.</span></footer></main></div></div>
}
